# Generated by Django 3.0.7 on 2020-08-10 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, max_length=250, null=True)),
                ('answer', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guidance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, max_length=260, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('reference_Id', models.CharField(default='1', max_length=100, primary_key=True, serialize=False)),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewPractice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, max_length=250, null=True)),
                ('answer', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('reference_Id', models.CharField(default='1', max_length=100, primary_key=True, serialize=False)),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
                ('experience', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumetempate', models.ImageField(blank=True, null=True, upload_to='Resume_Template')),
            ],
        ),
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.TextField(blank=True, max_length=260, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, max_length=250, null=True)),
                ('country', models.CharField(choices=[('India', 'India'), ('United States Of America', 'U.S.A'), ('United Kingdom', 'U.K'), ('Australia', 'Australia'), ('China', 'China'), ('Japan', 'Japan'), ('Canada', 'Canada'), ('Africa', 'Africa')], default='India', max_length=50)),
                ('resume', models.FileField(blank=True, null=True, upload_to='')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
